name: tdesign-pr-trigger-action
description: tdesign-pr-trigger-action
author: TDesign
inputs:
  owner:
    description: owner
    required: false
  repo:
    description: repo
    required: false
  pr_number:
    description: pr_number
    required: false
  trigger:
    description: trigger
    required: false
  token:
    description: token
    required: false
  dry-run:
    description: dry run
    required: false
  deps:
    description: deps
    required: false
  package-manager:
    description: package manager
    required: false
    default: npm

runs:
  using: node20
  main: dist/index.js
