import { defineConfig } from 'tsdown'
import packageJson from './package.json' with { type: 'json' }

export default defineConfig({
  entry: ['src/index.ts'],
  noExternal: [...Object.keys(packageJson.dependencies)],
  inlineOnly: [
    '@actions/core',
    '@actions/exec',
    '@actions/github',
    '@actions/http-client',
    '@actions/io',
    '@octokit/auth-token',
    '@octokit/core',
    '@octokit/endpoint',
    '@octokit/graphql',
    '@octokit/plugin-paginate-rest',
    '@octokit/plugin-rest-endpoint-methods',
    '@octokit/request',
    '@octokit/request-error',
    '@pnpm/constants',
    '@pnpm/error',
    '@pnpm/object.key-sorting',
    '@pnpm/ramda',
    '@pnpm/util.lex-comparator',
    '@pnpm/workspace.manifest-writer',
    '@pnpm/workspace.read-manifest',
    'before-after-hook',
    'fast-content-type-parse',
    'imurmurhash',
    'is-plain-obj',
    'js-yaml',
    'ky',
    'node-cnb',
    'read-yaml-file',
    'signal-exit',
    'sort-keys',
    'strip-bom',
    'tsdown',
    'tunnel',
    'undici',
    'universal-user-agent',
    'write-file-atomic',
    'write-yaml-file',
  ],
  shims: true,
})
