name: test-tdesign-icons-trigger
on:
  pull_request:
    branches: [develop]
    paths:
      - dist/*

jobs:
  pr-vue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: test
        uses: ./
        with:
          token: ${{ secrets.TDESIGN_BOT_TOKEN }}
          owner: Tencent
          repo: tdesign-icons
          pr_number: 231
          trigger: /pr-vue
          

  pr-vue-next:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: test
        uses: ./
        with:
          token: ${{ secrets.TDESIGN_BOT_TOKEN }}
          owner: Tencent
          repo: tdesign-icons
          pr_number: 231
          trigger: /pr-vue-next
          

  pr-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: test
        uses: ./
        with:
          token: ${{ secrets.TDESIGN_BOT_TOKEN }}
          owner: Tencent
          repo: tdesign-icons
          pr_number: 231
          trigger: /pr-react
          

  pr-mobile-vue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: test
        uses: ./
        with:
          token: ${{ secrets.TDESIGN_BOT_TOKEN }}
          owner: Tencent
          repo: tdesign-icons
          pr_number: 231
          trigger: /pr-mobile-vue
          

  pr-mobile-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: test
        uses: ./
        with:
          token: ${{ secrets.TDESIGN_BOT_TOKEN }}
          owner: Tencent
          repo: tdesign-icons
          pr_number: 231
          trigger: /pr-mobile-react
         

  pr-miniprogram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: test
        uses: ./
        with:
          token: ${{ secrets.TDESIGN_BOT_TOKEN }}
          owner: Tencent
          repo: tdesign-icons
          pr_number: 231
          trigger: /pr-miniprogram
          
