name: test-tdesign-icons-trigger
on:
  pull_request:
    branches: [develop]

jobs:
  pr-vue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 22

      - name: test
        uses: ./
        with:
          token: ${{ secrets.TDESIGN_BOT_TOKEN }}
          owner: Tencent
          repo: tdesign-icons
          pr_number: 233
          trigger: /pr-vue

  pr-vue-next:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 22

      - name: test
        uses: ./
        with:
          token: ${{ secrets.TDESIGN_BOT_TOKEN }}
          owner: Tencent
          repo: tdesign-icons
          pr_number: 233
          trigger: /pr-vue-next

  pr-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 22

      - name: test
        uses: ./
        with:
          token: ${{ secrets.TDESIGN_BOT_TOKEN }}
          owner: Tencent
          repo: tdesign-icons
          pr_number: 233
          trigger: /pr-react

  pr-mobile-vue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 22

      - name: test
        uses: ./
        with:
          token: ${{ secrets.TDESIGN_BOT_TOKEN }}
          owner: Tencent
          repo: tdesign-icons
          pr_number: 233
          trigger: /pr-mobile-vue

  pr-mobile-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 22

      - name: test
        uses: ./
        with:
          token: ${{ secrets.TDESIGN_BOT_TOKEN }}
          owner: Tencent
          repo: tdesign-icons
          pr_number: 233
          trigger: /pr-mobile-react

  pr-miniprogram:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 22

      - name: test
        uses: ./
        with:
          token: ${{ secrets.TDESIGN_BOT_TOKEN }}
          owner: Tencent
          repo: tdesign-icons
          pr_number: 233
          trigger: /pr-miniprogram
